const prompt = {
    "Movie": [
      "The Hobbit",
      "Harry Potter",
      "The Lord of the Rings",
      "Mulan",
      "The Lion King",
      "Beauty and the Beast",
      "Beauty and the Beast",
      "Star Wars",
      "The Jungle Book",
      "Jungle Book",
      "James Bond Series",
      "Alice in Wonderland",
      "Alice in Wonderland",
      "Cinderella",
      "Cinderella",
      "The Flash",
      "The Batman",
      "Doctor Strange in the Multiverse of Madness",
      "Thor: Love and Thunder",
      "Top Gun: Maverick",
      "Everything Everywhere All at Once",
      "Nope",
      "Black Adam",
      "Avatar: The Way of Water",
      "Jurassic World: Dominion",
      "Wednesday",
      "Dune",
      "Spider-Man: No Way Home",
      "Dune",
      "No Time to Die",
      "The Suicide Squad",
      "Shang-Chi and the Legend of the Ten Rings",
      "Eternals",
      "Spider-Man: No Way Home",
      "Encanto",
      "Luca",
      "The Mitchells vs. the Machines",
      "Soul",
      "1917",
      "Joker",
      "Once Upon a Time in Hollywood",
      "Parasite",
      "Avengers: Endgame",
      "Frozen II",
      "Toy Story 4",
      "A Quiet Place",
      "Annihilation",
      "Black Panther",
      "Bohemian Rhapsody",
      "First Man",
      "Green Book",
      "Hereditary",
      "Roma",
      "Spider-Man: Into the Spider-Verse",
      "Black Panther",
      "Spider-Man: Into the Spider-Verse",
      "Hereditary",
      "Bohemian Rhapsody",
      "Bird Box",
      "A Star Is Born",
      "Baby Driver",
      "Coco",
      "Dunkirk",
      "Get Out",
      "Logan",
      "The Florida Project",
      "The Shape of Water",
      "Wonder Woman",
      "Arrival",
      "Deadpool",
      "Finding Dory",
      "Hacksaw Ridge",
      "La La Land",
      "Moana",
      "Moonlight",
      "Nocturnal Animals",
      "Secret Life of Pets",
      "Sing",
      "The Secret Life of Pets",
      "Trolls",
      "Zootopia",
      "Zootopia",
      "Moana",
      "La La Land",
      "Moana",
      "Carol",
      "Inside Out",
      "Mad Max: Fury Road",
      "Minions",
      "Room",
      "The Big Short",
      "The Lobster",
      "The Revenant",
      "Big Hero 6",
      "Birdman",
      "Edge of Tomorrow",
      "Gone Girl",
      "Guardians of the Galaxy",
      "Interstellar",
      "Maleficent",
      "Nightcrawler",
      "The Grand Budapest Hotel",
      "The Imitation Game",
      "The Lego Movie",
      "Whiplash",
      "The Fault in Our Stars",
      "Guardians of the Galaxy",
      "Frozen",
      "Gravity",
      "Her",
      "Inside Llewyn Davis",
      "Prisoners",
      "Rush",
      "Frozen",
      "Brave",
      "Cloud Atlas",
      "Django Unchained",
      "Les Misérables",
      "Life of Pi",
      "Moonrise Kingdom",
      "Silver Linings Playbook",
      "Ted",
      "The Avengers",
      "The Hunger Games",
      "The Master",
      "Wreck-It Ralph",
      "The Perks of Being a Wallflower",
      "The Artist",
      "The Girl with the Dragon Tattoo",
      "Thor"
    ],
    "Songs": [
      "7 Rings",
      "A Sky Full of Stars",
      "Adore You",
      "Africa",
      "Ain't No Mountain High Enough",
      "All Along the Watchtower",
      "All Star",
      "American Pie",
      "Another Brick in the Wall",
      "Astronaut In The Ocean",
      "Attention",
      "Bad at Love",
      "Bad Guy",
      "Banana Pancakes",
      "Barbie Girl",
      "Beat It",
      "Beautiful Day",
      "Better",
      "Better Now",
      "Billie Jean",
      "Blackbird",
      "Blinding Lights",
      "Bohemian Rhapsody",
      "Born to Run",
      "Break My Heart",
      "Butter",
      "Californication",
      "Call Out My Name",
      "Can't Feel My Face",
      "Cardigan",
      "Castle on the Hill",
      "Chandelier",
      "Cheap Thrills",
      "Circles",
      "Come Together",
      "Dance Monkey",
      "Dancing Queen",
      "Deja Vu",
      "Despacito",
      "Don't Call Me Angel",
      "Don't Call Me Up",
      "Don't Let Me Down",
      "Don't Start Now",
      "Don’t Stop Believin’",
      "Dreams",
      "Drivers License",
      "Dusk Till Dawn",
      "Dynamite",
      "Easy On Me",
      "Everything I Wanted",
      "Exile",
      "Eye of the Tiger",
      "Feel It Still",
      "Firework",
      "Forever After All",
      "Free Bird",
      "Friends",
      "Gangsta's Paradise",
      "God's Plan",
      "Good 4 U",
      "Good as Hell",
      "Goodbyes",
      "Happier",
      "Happy",
      "Havana",
      "Head Above Water",
      "Heat Waves",
      "Hello",
      "Heroes",
      "Hey Jude",
      "Holy",
      "Hotel California",
      "Hotline Bling",
      "House of the Rising Sun",
      "I Don't Care",
      "I Gotta Feeling",
      "I Kissed a Girl",
      "I Like It",
      "I Will Always Love You",
      "If I Can't Have You",
      "Imagine",
      "In the End",
      "In the Mood",
      "Intentions",
      "Jolene",
      "Just the Way You Are",
      "Killing Me Softly",
      "Kings & Queens",
      "Leave The Door Open",
      "Let It Be",
      "Levitating",
      "Life Goes On",
      "Life on Mars?",
      "Like a Rolling Stone",
      "Livin' on a Prayer",
      "Lose You to Love Me",
      "Lose Yourself",
      "Losing My Religion",
      "Lost in Japan"
    ],
    "TV Shows": [
      "13 Reasons Why",
      "Better Call Saul",
      "Big Little Lies",
      "Black Mirror",
      "Breaking Bad",
      "Bridgerton",
      "Cobra Kai",
      "Dark",
      "Euphoria",
      "Fleabag",
      "Friends",
      "Game of Thrones",
      "Homeland",
      "Killing Eve",
      "Lost",
      "Lucifer",
      "Mad Men",
      "Mindhunter",
      "Money Heist",
      "Narcos",
      "Ozark",
      "Parks and Recreation",
      "Peaky Blinders",
      "Schitt's Creek",
      "Sherlock",
      "Stranger Things",
      "Succession",
      "The Big Bang Theory",
      "The Boys",
      "The Crown",
      "The Expanse",
      "The Good Place",
      "The Handmaid's Tale",
      "The Haunting of Hill House",
      "The Mandalorian",
      "The Marvelous Mrs. Maisel",
      "The Office",
      "The Queen's Gambit",
      "The Simpsons",
      "The Sopranos",
      "The Umbrella Academy",
      "The Walking Dead",
      "The West Wing",
      "The Wire",
      "The Witcher",
      "Twin Peaks",
      "Vikings",
      "Westworld"
    ]
  };
export default prompt;  